[project]
name = "excel-to-markdown-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown[xlsx]>=0.1.2",
    "pyinstaller>=6.15.0",
]
